### ISSUE TITLE
3%

### ISSUE THREAD

**Issue by alexey-hw** [slawiko/belarus_candidata_bot#1]
@slawiko more than **97%** among software engineers might think this is a bad idea
**https://github.com/slawiko/belarus_elections_2020_bot/blob/c205084dd774a803a2942855aac1fac4ce618e99/main.py#L71**

**Comment by slawiko** [comment]
Fixed in https://github.com/slawiko/belarus_elections_2020_bot/commit/8c19c6022a51b132bb927a08c3ad9c18eba8a46f
